# GENETARED BY NNDCT, DO NOT EDIT!

import torch
from torch import tensor
import pytorch_nndct as py_nndct

class SalsaNext(py_nndct.nn.NndctQuantModel):
    def __init__(self):
        super(SalsaNext, self).__init__()
        self.module_0 = py_nndct.nn.Input() #SalsaNext::input_0(SalsaNext::nndct_input_0)
        self.module_1 = py_nndct.nn.quant_input() #SalsaNext::SalsaNext/QuantStub[quant_stub]/12106(SalsaNext::nndct_quant_stub_1)
        self.module_2 = py_nndct.nn.Conv2d(in_channels=5, out_channels=32, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaEncoder[encoder]/ResContextBlock[downCntx]/Conv2d[conv1]/ret.5(SalsaNext::nndct_conv2d_2)
        self.module_3 = py_nndct.nn.Module('nndct_relu6',inplace=False) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaEncoder[encoder]/ResContextBlock[downCntx]/ReLU6[act1]/ret.7(SalsaNext::nndct_relu6_3)
        self.module_4 = py_nndct.nn.Conv2d(in_channels=32, out_channels=32, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaEncoder[encoder]/ResContextBlock[downCntx]/Conv2d[conv2]/ret.9(SalsaNext::nndct_conv2d_4)
        self.module_5 = py_nndct.nn.Module('nndct_relu6',inplace=False) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaEncoder[encoder]/ResContextBlock[downCntx]/ReLU6[act2]/ret.13(SalsaNext::nndct_relu6_5)
        self.module_6 = py_nndct.nn.Conv2d(in_channels=32, out_channels=32, kernel_size=[3, 3], stride=[1, 1], padding=[2, 2], dilation=[2, 2], groups=1, bias=True) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaEncoder[encoder]/ResContextBlock[downCntx]/Conv2d[conv3]/ret.15(SalsaNext::nndct_conv2d_6)
        self.module_7 = py_nndct.nn.Module('nndct_relu6',inplace=False) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaEncoder[encoder]/ResContextBlock[downCntx]/ReLU6[act3]/ret.19(SalsaNext::nndct_relu6_7)
        self.module_8 = py_nndct.nn.Add() #SalsaNext::SalsaNext/Salsa[salsa]/SalsaEncoder[encoder]/ResContextBlock[downCntx]/Add[skip_add]/ret.21(SalsaNext::nndct_elemwise_add_8)
        self.module_9 = py_nndct.nn.Conv2d(in_channels=32, out_channels=32, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaEncoder[encoder]/ResContextBlock[downCntx2]/Conv2d[conv1]/ret.23(SalsaNext::nndct_conv2d_9)
        self.module_10 = py_nndct.nn.Module('nndct_relu6',inplace=False) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaEncoder[encoder]/ResContextBlock[downCntx2]/ReLU6[act1]/ret.25(SalsaNext::nndct_relu6_10)
        self.module_11 = py_nndct.nn.Conv2d(in_channels=32, out_channels=32, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaEncoder[encoder]/ResContextBlock[downCntx2]/Conv2d[conv2]/ret.27(SalsaNext::nndct_conv2d_11)
        self.module_12 = py_nndct.nn.Module('nndct_relu6',inplace=False) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaEncoder[encoder]/ResContextBlock[downCntx2]/ReLU6[act2]/ret.31(SalsaNext::nndct_relu6_12)
        self.module_13 = py_nndct.nn.Conv2d(in_channels=32, out_channels=32, kernel_size=[3, 3], stride=[1, 1], padding=[2, 2], dilation=[2, 2], groups=1, bias=True) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaEncoder[encoder]/ResContextBlock[downCntx2]/Conv2d[conv3]/ret.33(SalsaNext::nndct_conv2d_13)
        self.module_14 = py_nndct.nn.Module('nndct_relu6',inplace=False) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaEncoder[encoder]/ResContextBlock[downCntx2]/ReLU6[act3]/ret.37(SalsaNext::nndct_relu6_14)
        self.module_15 = py_nndct.nn.Add() #SalsaNext::SalsaNext/Salsa[salsa]/SalsaEncoder[encoder]/ResContextBlock[downCntx2]/Add[skip_add]/ret.39(SalsaNext::nndct_elemwise_add_15)
        self.module_16 = py_nndct.nn.Conv2d(in_channels=32, out_channels=32, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaEncoder[encoder]/ResContextBlock[downCntx3]/Conv2d[conv1]/ret.41(SalsaNext::nndct_conv2d_16)
        self.module_17 = py_nndct.nn.Module('nndct_relu6',inplace=False) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaEncoder[encoder]/ResContextBlock[downCntx3]/ReLU6[act1]/ret.43(SalsaNext::nndct_relu6_17)
        self.module_18 = py_nndct.nn.Conv2d(in_channels=32, out_channels=32, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaEncoder[encoder]/ResContextBlock[downCntx3]/Conv2d[conv2]/ret.45(SalsaNext::nndct_conv2d_18)
        self.module_19 = py_nndct.nn.Module('nndct_relu6',inplace=False) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaEncoder[encoder]/ResContextBlock[downCntx3]/ReLU6[act2]/ret.49(SalsaNext::nndct_relu6_19)
        self.module_20 = py_nndct.nn.Conv2d(in_channels=32, out_channels=32, kernel_size=[3, 3], stride=[1, 1], padding=[2, 2], dilation=[2, 2], groups=1, bias=True) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaEncoder[encoder]/ResContextBlock[downCntx3]/Conv2d[conv3]/ret.51(SalsaNext::nndct_conv2d_20)
        self.module_21 = py_nndct.nn.Module('nndct_relu6',inplace=False) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaEncoder[encoder]/ResContextBlock[downCntx3]/ReLU6[act3]/ret.55(SalsaNext::nndct_relu6_21)
        self.module_22 = py_nndct.nn.Add() #SalsaNext::SalsaNext/Salsa[salsa]/SalsaEncoder[encoder]/ResContextBlock[downCntx3]/Add[skip_add]/ret.57(SalsaNext::nndct_elemwise_add_22)
        self.module_23 = py_nndct.nn.Conv2d(in_channels=32, out_channels=64, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaEncoder[encoder]/ResBlock[resBlock1]/Conv2d[conv1]/ret.59(SalsaNext::nndct_conv2d_23)
        self.module_24 = py_nndct.nn.Module('nndct_relu6',inplace=False) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaEncoder[encoder]/ResBlock[resBlock1]/ReLU6[act1]/ret.61(SalsaNext::nndct_relu6_24)
        self.module_25 = py_nndct.nn.Conv2d(in_channels=32, out_channels=64, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaEncoder[encoder]/ResBlock[resBlock1]/Conv2d[conv2]/ret.63(SalsaNext::nndct_conv2d_25)
        self.module_26 = py_nndct.nn.Module('nndct_relu6',inplace=False) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaEncoder[encoder]/ResBlock[resBlock1]/ReLU6[act2]/ret.67(SalsaNext::nndct_relu6_26)
        self.module_27 = py_nndct.nn.Conv2d(in_channels=64, out_channels=64, kernel_size=[3, 3], stride=[1, 1], padding=[2, 2], dilation=[2, 2], groups=1, bias=True) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaEncoder[encoder]/ResBlock[resBlock1]/Conv2d[conv3]/ret.69(SalsaNext::nndct_conv2d_27)
        self.module_28 = py_nndct.nn.Module('nndct_relu6',inplace=False) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaEncoder[encoder]/ResBlock[resBlock1]/ReLU6[act3]/ret.73(SalsaNext::nndct_relu6_28)
        self.module_29 = py_nndct.nn.Conv2d(in_channels=64, out_channels=64, kernel_size=[2, 2], stride=[1, 1], padding=[1, 1], dilation=[2, 2], groups=1, bias=True) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaEncoder[encoder]/ResBlock[resBlock1]/Conv2d[conv4]/ret.75(SalsaNext::nndct_conv2d_29)
        self.module_30 = py_nndct.nn.Module('nndct_relu6',inplace=False) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaEncoder[encoder]/ResBlock[resBlock1]/ReLU6[act4]/ret.79(SalsaNext::nndct_relu6_30)
        self.module_31 = py_nndct.nn.Cat() #SalsaNext::SalsaNext/Salsa[salsa]/SalsaEncoder[encoder]/ResBlock[resBlock1]/Cat[cat]/ret.81(SalsaNext::nndct_concat_31)
        self.module_32 = py_nndct.nn.Conv2d(in_channels=192, out_channels=64, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaEncoder[encoder]/ResBlock[resBlock1]/Conv2d[conv5]/ret.83(SalsaNext::nndct_conv2d_32)
        self.module_33 = py_nndct.nn.Module('nndct_relu6',inplace=False) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaEncoder[encoder]/ResBlock[resBlock1]/ReLU6[act5]/ret.87(SalsaNext::nndct_relu6_33)
        self.module_34 = py_nndct.nn.Add() #SalsaNext::SalsaNext/Salsa[salsa]/SalsaEncoder[encoder]/ResBlock[resBlock1]/Add[skip_add]/ret.89(SalsaNext::nndct_elemwise_add_34)
        self.module_35 = py_nndct.nn.AvgPool2d(kernel_size=[3, 3], stride=[2, 2], padding=[1, 1], ceil_mode=False, count_include_pad=True) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaEncoder[encoder]/ResBlock[resBlock1]/AvgPool2d[pool]/12535(SalsaNext::nndct_avgpool_35)
        self.module_36 = py_nndct.nn.Conv2d(in_channels=64, out_channels=128, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaEncoder[encoder]/ResBlock[resBlock2]/Conv2d[conv1]/ret.91(SalsaNext::nndct_conv2d_36)
        self.module_37 = py_nndct.nn.Module('nndct_relu6',inplace=False) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaEncoder[encoder]/ResBlock[resBlock2]/ReLU6[act1]/ret.93(SalsaNext::nndct_relu6_37)
        self.module_38 = py_nndct.nn.Conv2d(in_channels=64, out_channels=128, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaEncoder[encoder]/ResBlock[resBlock2]/Conv2d[conv2]/ret.95(SalsaNext::nndct_conv2d_38)
        self.module_39 = py_nndct.nn.Module('nndct_relu6',inplace=False) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaEncoder[encoder]/ResBlock[resBlock2]/ReLU6[act2]/ret.99(SalsaNext::nndct_relu6_39)
        self.module_40 = py_nndct.nn.Conv2d(in_channels=128, out_channels=128, kernel_size=[3, 3], stride=[1, 1], padding=[2, 2], dilation=[2, 2], groups=1, bias=True) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaEncoder[encoder]/ResBlock[resBlock2]/Conv2d[conv3]/ret.101(SalsaNext::nndct_conv2d_40)
        self.module_41 = py_nndct.nn.Module('nndct_relu6',inplace=False) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaEncoder[encoder]/ResBlock[resBlock2]/ReLU6[act3]/ret.105(SalsaNext::nndct_relu6_41)
        self.module_42 = py_nndct.nn.Conv2d(in_channels=128, out_channels=128, kernel_size=[2, 2], stride=[1, 1], padding=[1, 1], dilation=[2, 2], groups=1, bias=True) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaEncoder[encoder]/ResBlock[resBlock2]/Conv2d[conv4]/ret.107(SalsaNext::nndct_conv2d_42)
        self.module_43 = py_nndct.nn.Module('nndct_relu6',inplace=False) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaEncoder[encoder]/ResBlock[resBlock2]/ReLU6[act4]/ret.111(SalsaNext::nndct_relu6_43)
        self.module_44 = py_nndct.nn.Cat() #SalsaNext::SalsaNext/Salsa[salsa]/SalsaEncoder[encoder]/ResBlock[resBlock2]/Cat[cat]/ret.113(SalsaNext::nndct_concat_44)
        self.module_45 = py_nndct.nn.Conv2d(in_channels=384, out_channels=128, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaEncoder[encoder]/ResBlock[resBlock2]/Conv2d[conv5]/ret.115(SalsaNext::nndct_conv2d_45)
        self.module_46 = py_nndct.nn.Module('nndct_relu6',inplace=False) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaEncoder[encoder]/ResBlock[resBlock2]/ReLU6[act5]/ret.119(SalsaNext::nndct_relu6_46)
        self.module_47 = py_nndct.nn.Add() #SalsaNext::SalsaNext/Salsa[salsa]/SalsaEncoder[encoder]/ResBlock[resBlock2]/Add[skip_add]/ret.121(SalsaNext::nndct_elemwise_add_47)
        self.module_48 = py_nndct.nn.AvgPool2d(kernel_size=[3, 3], stride=[2, 2], padding=[1, 1], ceil_mode=False, count_include_pad=True) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaEncoder[encoder]/ResBlock[resBlock2]/AvgPool2d[pool]/12707(SalsaNext::nndct_avgpool_48)
        self.module_49 = py_nndct.nn.Conv2d(in_channels=128, out_channels=256, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaEncoder[encoder]/ResBlock[resBlock3]/Conv2d[conv1]/ret.123(SalsaNext::nndct_conv2d_49)
        self.module_50 = py_nndct.nn.Module('nndct_relu6',inplace=False) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaEncoder[encoder]/ResBlock[resBlock3]/ReLU6[act1]/ret.125(SalsaNext::nndct_relu6_50)
        self.module_51 = py_nndct.nn.Conv2d(in_channels=128, out_channels=256, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaEncoder[encoder]/ResBlock[resBlock3]/Conv2d[conv2]/ret.127(SalsaNext::nndct_conv2d_51)
        self.module_52 = py_nndct.nn.Module('nndct_relu6',inplace=False) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaEncoder[encoder]/ResBlock[resBlock3]/ReLU6[act2]/ret.131(SalsaNext::nndct_relu6_52)
        self.module_53 = py_nndct.nn.Conv2d(in_channels=256, out_channels=256, kernel_size=[3, 3], stride=[1, 1], padding=[2, 2], dilation=[2, 2], groups=1, bias=True) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaEncoder[encoder]/ResBlock[resBlock3]/Conv2d[conv3]/ret.133(SalsaNext::nndct_conv2d_53)
        self.module_54 = py_nndct.nn.Module('nndct_relu6',inplace=False) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaEncoder[encoder]/ResBlock[resBlock3]/ReLU6[act3]/ret.137(SalsaNext::nndct_relu6_54)
        self.module_55 = py_nndct.nn.Conv2d(in_channels=256, out_channels=256, kernel_size=[2, 2], stride=[1, 1], padding=[1, 1], dilation=[2, 2], groups=1, bias=True) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaEncoder[encoder]/ResBlock[resBlock3]/Conv2d[conv4]/ret.139(SalsaNext::nndct_conv2d_55)
        self.module_56 = py_nndct.nn.Module('nndct_relu6',inplace=False) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaEncoder[encoder]/ResBlock[resBlock3]/ReLU6[act4]/ret.143(SalsaNext::nndct_relu6_56)
        self.module_57 = py_nndct.nn.Cat() #SalsaNext::SalsaNext/Salsa[salsa]/SalsaEncoder[encoder]/ResBlock[resBlock3]/Cat[cat]/ret.145(SalsaNext::nndct_concat_57)
        self.module_58 = py_nndct.nn.Conv2d(in_channels=768, out_channels=256, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaEncoder[encoder]/ResBlock[resBlock3]/Conv2d[conv5]/ret.147(SalsaNext::nndct_conv2d_58)
        self.module_59 = py_nndct.nn.Module('nndct_relu6',inplace=False) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaEncoder[encoder]/ResBlock[resBlock3]/ReLU6[act5]/ret.151(SalsaNext::nndct_relu6_59)
        self.module_60 = py_nndct.nn.Add() #SalsaNext::SalsaNext/Salsa[salsa]/SalsaEncoder[encoder]/ResBlock[resBlock3]/Add[skip_add]/ret.153(SalsaNext::nndct_elemwise_add_60)
        self.module_61 = py_nndct.nn.AvgPool2d(kernel_size=[3, 3], stride=[2, 2], padding=[1, 1], ceil_mode=False, count_include_pad=True) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaEncoder[encoder]/ResBlock[resBlock3]/AvgPool2d[pool]/12879(SalsaNext::nndct_avgpool_61)
        self.module_62 = py_nndct.nn.Conv2d(in_channels=256, out_channels=256, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaEncoder[encoder]/ResBlock[resBlock4]/Conv2d[conv1]/ret.155(SalsaNext::nndct_conv2d_62)
        self.module_63 = py_nndct.nn.Module('nndct_relu6',inplace=False) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaEncoder[encoder]/ResBlock[resBlock4]/ReLU6[act1]/ret.157(SalsaNext::nndct_relu6_63)
        self.module_64 = py_nndct.nn.Conv2d(in_channels=256, out_channels=256, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaEncoder[encoder]/ResBlock[resBlock4]/Conv2d[conv2]/ret.159(SalsaNext::nndct_conv2d_64)
        self.module_65 = py_nndct.nn.Module('nndct_relu6',inplace=False) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaEncoder[encoder]/ResBlock[resBlock4]/ReLU6[act2]/ret.163(SalsaNext::nndct_relu6_65)
        self.module_66 = py_nndct.nn.Conv2d(in_channels=256, out_channels=256, kernel_size=[3, 3], stride=[1, 1], padding=[2, 2], dilation=[2, 2], groups=1, bias=True) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaEncoder[encoder]/ResBlock[resBlock4]/Conv2d[conv3]/ret.165(SalsaNext::nndct_conv2d_66)
        self.module_67 = py_nndct.nn.Module('nndct_relu6',inplace=False) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaEncoder[encoder]/ResBlock[resBlock4]/ReLU6[act3]/ret.169(SalsaNext::nndct_relu6_67)
        self.module_68 = py_nndct.nn.Conv2d(in_channels=256, out_channels=256, kernel_size=[2, 2], stride=[1, 1], padding=[1, 1], dilation=[2, 2], groups=1, bias=True) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaEncoder[encoder]/ResBlock[resBlock4]/Conv2d[conv4]/ret.171(SalsaNext::nndct_conv2d_68)
        self.module_69 = py_nndct.nn.Module('nndct_relu6',inplace=False) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaEncoder[encoder]/ResBlock[resBlock4]/ReLU6[act4]/ret.175(SalsaNext::nndct_relu6_69)
        self.module_70 = py_nndct.nn.Cat() #SalsaNext::SalsaNext/Salsa[salsa]/SalsaEncoder[encoder]/ResBlock[resBlock4]/Cat[cat]/ret.177(SalsaNext::nndct_concat_70)
        self.module_71 = py_nndct.nn.Conv2d(in_channels=768, out_channels=256, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaEncoder[encoder]/ResBlock[resBlock4]/Conv2d[conv5]/ret.179(SalsaNext::nndct_conv2d_71)
        self.module_72 = py_nndct.nn.Module('nndct_relu6',inplace=False) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaEncoder[encoder]/ResBlock[resBlock4]/ReLU6[act5]/ret.183(SalsaNext::nndct_relu6_72)
        self.module_73 = py_nndct.nn.Add() #SalsaNext::SalsaNext/Salsa[salsa]/SalsaEncoder[encoder]/ResBlock[resBlock4]/Add[skip_add]/ret.185(SalsaNext::nndct_elemwise_add_73)
        self.module_74 = py_nndct.nn.AvgPool2d(kernel_size=[3, 3], stride=[2, 2], padding=[1, 1], ceil_mode=False, count_include_pad=True) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaEncoder[encoder]/ResBlock[resBlock4]/AvgPool2d[pool]/13051(SalsaNext::nndct_avgpool_74)
        self.module_75 = py_nndct.nn.Conv2d(in_channels=256, out_channels=256, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaEncoder[encoder]/ResBlock[resBlock5]/Conv2d[conv1]/ret.187(SalsaNext::nndct_conv2d_75)
        self.module_76 = py_nndct.nn.Module('nndct_relu6',inplace=False) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaEncoder[encoder]/ResBlock[resBlock5]/ReLU6[act1]/ret.189(SalsaNext::nndct_relu6_76)
        self.module_77 = py_nndct.nn.Conv2d(in_channels=256, out_channels=256, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaEncoder[encoder]/ResBlock[resBlock5]/Conv2d[conv2]/ret.191(SalsaNext::nndct_conv2d_77)
        self.module_78 = py_nndct.nn.Module('nndct_relu6',inplace=False) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaEncoder[encoder]/ResBlock[resBlock5]/ReLU6[act2]/ret.195(SalsaNext::nndct_relu6_78)
        self.module_79 = py_nndct.nn.Conv2d(in_channels=256, out_channels=256, kernel_size=[3, 3], stride=[1, 1], padding=[2, 2], dilation=[2, 2], groups=1, bias=True) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaEncoder[encoder]/ResBlock[resBlock5]/Conv2d[conv3]/ret.197(SalsaNext::nndct_conv2d_79)
        self.module_80 = py_nndct.nn.Module('nndct_relu6',inplace=False) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaEncoder[encoder]/ResBlock[resBlock5]/ReLU6[act3]/ret.201(SalsaNext::nndct_relu6_80)
        self.module_81 = py_nndct.nn.Conv2d(in_channels=256, out_channels=256, kernel_size=[2, 2], stride=[1, 1], padding=[1, 1], dilation=[2, 2], groups=1, bias=True) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaEncoder[encoder]/ResBlock[resBlock5]/Conv2d[conv4]/ret.203(SalsaNext::nndct_conv2d_81)
        self.module_82 = py_nndct.nn.Module('nndct_relu6',inplace=False) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaEncoder[encoder]/ResBlock[resBlock5]/ReLU6[act4]/ret.207(SalsaNext::nndct_relu6_82)
        self.module_83 = py_nndct.nn.Cat() #SalsaNext::SalsaNext/Salsa[salsa]/SalsaEncoder[encoder]/ResBlock[resBlock5]/Cat[cat]/ret.209(SalsaNext::nndct_concat_83)
        self.module_84 = py_nndct.nn.Conv2d(in_channels=768, out_channels=256, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaEncoder[encoder]/ResBlock[resBlock5]/Conv2d[conv5]/ret.211(SalsaNext::nndct_conv2d_84)
        self.module_85 = py_nndct.nn.Module('nndct_relu6',inplace=False) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaEncoder[encoder]/ResBlock[resBlock5]/ReLU6[act5]/ret.215(SalsaNext::nndct_relu6_85)
        self.module_86 = py_nndct.nn.Add() #SalsaNext::SalsaNext/Salsa[salsa]/SalsaEncoder[encoder]/ResBlock[resBlock5]/Add[skip_add]/ret.217(SalsaNext::nndct_elemwise_add_86)
        self.module_87 = py_nndct.nn.Interpolate() #SalsaNext::SalsaNext/Salsa[salsa]/SalsaDecoder[decoder]/UpBlock[upBlock1]/Upsample[up]/ret.219(SalsaNext::nndct_resize_87)
        self.module_88 = py_nndct.nn.Conv2d(in_channels=256, out_channels=64, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaDecoder[decoder]/UpBlock[upBlock1]/Conv2d[convup]/ret.221(SalsaNext::nndct_conv2d_88)
        self.module_89 = py_nndct.nn.Module('nndct_relu6',inplace=False) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaDecoder[decoder]/UpBlock[upBlock1]/ReLU6[actup]/ret.225(SalsaNext::nndct_relu6_89)
        self.module_90 = py_nndct.nn.Cat() #SalsaNext::SalsaNext/Salsa[salsa]/SalsaDecoder[decoder]/UpBlock[upBlock1]/Cat[cat1]/ret.227(SalsaNext::nndct_concat_90)
        self.module_91 = py_nndct.nn.Conv2d(in_channels=320, out_channels=128, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaDecoder[decoder]/UpBlock[upBlock1]/Conv2d[conv1]/ret.229(SalsaNext::nndct_conv2d_91)
        self.module_92 = py_nndct.nn.Module('nndct_relu6',inplace=False) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaDecoder[decoder]/UpBlock[upBlock1]/ReLU6[act1]/ret.233(SalsaNext::nndct_relu6_92)
        self.module_93 = py_nndct.nn.Conv2d(in_channels=128, out_channels=128, kernel_size=[3, 3], stride=[1, 1], padding=[2, 2], dilation=[2, 2], groups=1, bias=True) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaDecoder[decoder]/UpBlock[upBlock1]/Conv2d[conv2]/ret.235(SalsaNext::nndct_conv2d_93)
        self.module_94 = py_nndct.nn.Module('nndct_relu6',inplace=False) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaDecoder[decoder]/UpBlock[upBlock1]/ReLU6[act2]/ret.239(SalsaNext::nndct_relu6_94)
        self.module_95 = py_nndct.nn.Conv2d(in_channels=128, out_channels=128, kernel_size=[2, 2], stride=[1, 1], padding=[1, 1], dilation=[2, 2], groups=1, bias=True) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaDecoder[decoder]/UpBlock[upBlock1]/Conv2d[conv3]/ret.241(SalsaNext::nndct_conv2d_95)
        self.module_96 = py_nndct.nn.Module('nndct_relu6',inplace=False) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaDecoder[decoder]/UpBlock[upBlock1]/ReLU6[act3]/ret.245(SalsaNext::nndct_relu6_96)
        self.module_97 = py_nndct.nn.Cat() #SalsaNext::SalsaNext/Salsa[salsa]/SalsaDecoder[decoder]/UpBlock[upBlock1]/Cat[cat2]/ret.247(SalsaNext::nndct_concat_97)
        self.module_98 = py_nndct.nn.Conv2d(in_channels=384, out_channels=128, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaDecoder[decoder]/UpBlock[upBlock1]/Conv2d[conv4]/ret.249(SalsaNext::nndct_conv2d_98)
        self.module_99 = py_nndct.nn.Module('nndct_relu6',inplace=False) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaDecoder[decoder]/UpBlock[upBlock1]/ReLU6[act4]/ret.253(SalsaNext::nndct_relu6_99)
        self.module_100 = py_nndct.nn.Interpolate() #SalsaNext::SalsaNext/Salsa[salsa]/SalsaDecoder[decoder]/UpBlock[upBlock2]/Upsample[up]/ret.255(SalsaNext::nndct_resize_100)
        self.module_101 = py_nndct.nn.Conv2d(in_channels=128, out_channels=32, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaDecoder[decoder]/UpBlock[upBlock2]/Conv2d[convup]/ret.257(SalsaNext::nndct_conv2d_101)
        self.module_102 = py_nndct.nn.Module('nndct_relu6',inplace=False) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaDecoder[decoder]/UpBlock[upBlock2]/ReLU6[actup]/ret.261(SalsaNext::nndct_relu6_102)
        self.module_103 = py_nndct.nn.Cat() #SalsaNext::SalsaNext/Salsa[salsa]/SalsaDecoder[decoder]/UpBlock[upBlock2]/Cat[cat1]/ret.263(SalsaNext::nndct_concat_103)
        self.module_104 = py_nndct.nn.Conv2d(in_channels=288, out_channels=128, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaDecoder[decoder]/UpBlock[upBlock2]/Conv2d[conv1]/ret.265(SalsaNext::nndct_conv2d_104)
        self.module_105 = py_nndct.nn.Module('nndct_relu6',inplace=False) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaDecoder[decoder]/UpBlock[upBlock2]/ReLU6[act1]/ret.269(SalsaNext::nndct_relu6_105)
        self.module_106 = py_nndct.nn.Conv2d(in_channels=128, out_channels=128, kernel_size=[3, 3], stride=[1, 1], padding=[2, 2], dilation=[2, 2], groups=1, bias=True) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaDecoder[decoder]/UpBlock[upBlock2]/Conv2d[conv2]/ret.271(SalsaNext::nndct_conv2d_106)
        self.module_107 = py_nndct.nn.Module('nndct_relu6',inplace=False) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaDecoder[decoder]/UpBlock[upBlock2]/ReLU6[act2]/ret.275(SalsaNext::nndct_relu6_107)
        self.module_108 = py_nndct.nn.Conv2d(in_channels=128, out_channels=128, kernel_size=[2, 2], stride=[1, 1], padding=[1, 1], dilation=[2, 2], groups=1, bias=True) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaDecoder[decoder]/UpBlock[upBlock2]/Conv2d[conv3]/ret.277(SalsaNext::nndct_conv2d_108)
        self.module_109 = py_nndct.nn.Module('nndct_relu6',inplace=False) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaDecoder[decoder]/UpBlock[upBlock2]/ReLU6[act3]/ret.281(SalsaNext::nndct_relu6_109)
        self.module_110 = py_nndct.nn.Cat() #SalsaNext::SalsaNext/Salsa[salsa]/SalsaDecoder[decoder]/UpBlock[upBlock2]/Cat[cat2]/ret.283(SalsaNext::nndct_concat_110)
        self.module_111 = py_nndct.nn.Conv2d(in_channels=384, out_channels=128, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaDecoder[decoder]/UpBlock[upBlock2]/Conv2d[conv4]/ret.285(SalsaNext::nndct_conv2d_111)
        self.module_112 = py_nndct.nn.Module('nndct_relu6',inplace=False) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaDecoder[decoder]/UpBlock[upBlock2]/ReLU6[act4]/ret.289(SalsaNext::nndct_relu6_112)
        self.module_113 = py_nndct.nn.Interpolate() #SalsaNext::SalsaNext/Salsa[salsa]/SalsaDecoder[decoder]/UpBlock[upBlock3]/Upsample[up]/ret.291(SalsaNext::nndct_resize_113)
        self.module_114 = py_nndct.nn.Conv2d(in_channels=128, out_channels=32, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaDecoder[decoder]/UpBlock[upBlock3]/Conv2d[convup]/ret.293(SalsaNext::nndct_conv2d_114)
        self.module_115 = py_nndct.nn.Module('nndct_relu6',inplace=False) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaDecoder[decoder]/UpBlock[upBlock3]/ReLU6[actup]/ret.297(SalsaNext::nndct_relu6_115)
        self.module_116 = py_nndct.nn.Cat() #SalsaNext::SalsaNext/Salsa[salsa]/SalsaDecoder[decoder]/UpBlock[upBlock3]/Cat[cat1]/ret.299(SalsaNext::nndct_concat_116)
        self.module_117 = py_nndct.nn.Conv2d(in_channels=160, out_channels=64, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaDecoder[decoder]/UpBlock[upBlock3]/Conv2d[conv1]/ret.301(SalsaNext::nndct_conv2d_117)
        self.module_118 = py_nndct.nn.Module('nndct_relu6',inplace=False) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaDecoder[decoder]/UpBlock[upBlock3]/ReLU6[act1]/ret.305(SalsaNext::nndct_relu6_118)
        self.module_119 = py_nndct.nn.Conv2d(in_channels=64, out_channels=64, kernel_size=[3, 3], stride=[1, 1], padding=[2, 2], dilation=[2, 2], groups=1, bias=True) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaDecoder[decoder]/UpBlock[upBlock3]/Conv2d[conv2]/ret.307(SalsaNext::nndct_conv2d_119)
        self.module_120 = py_nndct.nn.Module('nndct_relu6',inplace=False) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaDecoder[decoder]/UpBlock[upBlock3]/ReLU6[act2]/ret.311(SalsaNext::nndct_relu6_120)
        self.module_121 = py_nndct.nn.Conv2d(in_channels=64, out_channels=64, kernel_size=[2, 2], stride=[1, 1], padding=[1, 1], dilation=[2, 2], groups=1, bias=True) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaDecoder[decoder]/UpBlock[upBlock3]/Conv2d[conv3]/ret.313(SalsaNext::nndct_conv2d_121)
        self.module_122 = py_nndct.nn.Module('nndct_relu6',inplace=False) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaDecoder[decoder]/UpBlock[upBlock3]/ReLU6[act3]/ret.317(SalsaNext::nndct_relu6_122)
        self.module_123 = py_nndct.nn.Cat() #SalsaNext::SalsaNext/Salsa[salsa]/SalsaDecoder[decoder]/UpBlock[upBlock3]/Cat[cat2]/ret.319(SalsaNext::nndct_concat_123)
        self.module_124 = py_nndct.nn.Conv2d(in_channels=192, out_channels=64, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaDecoder[decoder]/UpBlock[upBlock3]/Conv2d[conv4]/ret.321(SalsaNext::nndct_conv2d_124)
        self.module_125 = py_nndct.nn.Module('nndct_relu6',inplace=False) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaDecoder[decoder]/UpBlock[upBlock3]/ReLU6[act4]/ret.325(SalsaNext::nndct_relu6_125)
        self.module_126 = py_nndct.nn.Interpolate() #SalsaNext::SalsaNext/Salsa[salsa]/SalsaDecoder[decoder]/UpBlock[upBlock4]/Upsample[up]/ret.327(SalsaNext::nndct_resize_126)
        self.module_127 = py_nndct.nn.Conv2d(in_channels=64, out_channels=16, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaDecoder[decoder]/UpBlock[upBlock4]/Conv2d[convup]/ret.329(SalsaNext::nndct_conv2d_127)
        self.module_128 = py_nndct.nn.Module('nndct_relu6',inplace=False) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaDecoder[decoder]/UpBlock[upBlock4]/ReLU6[actup]/ret.333(SalsaNext::nndct_relu6_128)
        self.module_129 = py_nndct.nn.Cat() #SalsaNext::SalsaNext/Salsa[salsa]/SalsaDecoder[decoder]/UpBlock[upBlock4]/Cat[cat1]/ret.335(SalsaNext::nndct_concat_129)
        self.module_130 = py_nndct.nn.Conv2d(in_channels=80, out_channels=32, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaDecoder[decoder]/UpBlock[upBlock4]/Conv2d[conv1]/ret.337(SalsaNext::nndct_conv2d_130)
        self.module_131 = py_nndct.nn.Module('nndct_relu6',inplace=False) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaDecoder[decoder]/UpBlock[upBlock4]/ReLU6[act1]/ret.341(SalsaNext::nndct_relu6_131)
        self.module_132 = py_nndct.nn.Conv2d(in_channels=32, out_channels=32, kernel_size=[3, 3], stride=[1, 1], padding=[2, 2], dilation=[2, 2], groups=1, bias=True) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaDecoder[decoder]/UpBlock[upBlock4]/Conv2d[conv2]/ret.343(SalsaNext::nndct_conv2d_132)
        self.module_133 = py_nndct.nn.Module('nndct_relu6',inplace=False) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaDecoder[decoder]/UpBlock[upBlock4]/ReLU6[act2]/ret.347(SalsaNext::nndct_relu6_133)
        self.module_134 = py_nndct.nn.Conv2d(in_channels=32, out_channels=32, kernel_size=[2, 2], stride=[1, 1], padding=[1, 1], dilation=[2, 2], groups=1, bias=True) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaDecoder[decoder]/UpBlock[upBlock4]/Conv2d[conv3]/ret.349(SalsaNext::nndct_conv2d_134)
        self.module_135 = py_nndct.nn.Module('nndct_relu6',inplace=False) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaDecoder[decoder]/UpBlock[upBlock4]/ReLU6[act3]/ret.353(SalsaNext::nndct_relu6_135)
        self.module_136 = py_nndct.nn.Cat() #SalsaNext::SalsaNext/Salsa[salsa]/SalsaDecoder[decoder]/UpBlock[upBlock4]/Cat[cat2]/ret.355(SalsaNext::nndct_concat_136)
        self.module_137 = py_nndct.nn.Conv2d(in_channels=96, out_channels=32, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaDecoder[decoder]/UpBlock[upBlock4]/Conv2d[conv4]/ret.357(SalsaNext::nndct_conv2d_137)
        self.module_138 = py_nndct.nn.Module('nndct_relu6',inplace=False) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaDecoder[decoder]/UpBlock[upBlock4]/ReLU6[act4]/ret.361(SalsaNext::nndct_relu6_138)
        self.module_139 = py_nndct.nn.Conv2d(in_channels=32, out_channels=20, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #SalsaNext::SalsaNext/Salsa[salsa]/SalsaDecoder[decoder]/Conv2d[logits]/ret.363(SalsaNext::nndct_conv2d_139)
        self.module_140 = py_nndct.nn.dequant_output() #SalsaNext::SalsaNext/DeQuantStub[dequant_stub]/13923(SalsaNext::nndct_dequant_stub_140)
        self.module_141 = py_nndct.nn.Softmax(dim=1) #SalsaNext::SalsaNext/ret(SalsaNext::nndct_softmax_141)

    @py_nndct.nn.forward_processor
    def forward(self, *args):
        output_module_0 = self.module_0(input=args[0])
        output_module_0 = self.module_1(input=output_module_0)
        output_module_0 = self.module_2(output_module_0)
        output_module_0 = self.module_3(output_module_0)
        output_module_4 = self.module_4(output_module_0)
        output_module_4 = self.module_5(output_module_4)
        output_module_4 = self.module_6(output_module_4)
        output_module_4 = self.module_7(output_module_4)
        output_module_8 = self.module_8(input=output_module_0, other=output_module_4, alpha=1)
        output_module_8 = self.module_9(output_module_8)
        output_module_8 = self.module_10(output_module_8)
        output_module_11 = self.module_11(output_module_8)
        output_module_11 = self.module_12(output_module_11)
        output_module_11 = self.module_13(output_module_11)
        output_module_11 = self.module_14(output_module_11)
        output_module_15 = self.module_15(input=output_module_8, other=output_module_11, alpha=1)
        output_module_15 = self.module_16(output_module_15)
        output_module_15 = self.module_17(output_module_15)
        output_module_18 = self.module_18(output_module_15)
        output_module_18 = self.module_19(output_module_18)
        output_module_18 = self.module_20(output_module_18)
        output_module_18 = self.module_21(output_module_18)
        output_module_22 = self.module_22(input=output_module_15, other=output_module_18, alpha=1)
        output_module_23 = self.module_23(output_module_22)
        output_module_23 = self.module_24(output_module_23)
        output_module_25 = self.module_25(output_module_22)
        output_module_25 = self.module_26(output_module_25)
        output_module_27 = self.module_27(output_module_25)
        output_module_27 = self.module_28(output_module_27)
        output_module_29 = self.module_29(output_module_27)
        output_module_29 = self.module_30(output_module_29)
        output_module_31 = self.module_31(dim=1, tensors=[output_module_25,output_module_27,output_module_29])
        output_module_31 = self.module_32(output_module_31)
        output_module_31 = self.module_33(output_module_31)
        output_module_23 = self.module_34(input=output_module_23, other=output_module_31, alpha=1)
        output_module_35 = self.module_35(output_module_23)
        output_module_36 = self.module_36(output_module_35)
        output_module_36 = self.module_37(output_module_36)
        output_module_38 = self.module_38(output_module_35)
        output_module_38 = self.module_39(output_module_38)
        output_module_40 = self.module_40(output_module_38)
        output_module_40 = self.module_41(output_module_40)
        output_module_42 = self.module_42(output_module_40)
        output_module_42 = self.module_43(output_module_42)
        output_module_44 = self.module_44(dim=1, tensors=[output_module_38,output_module_40,output_module_42])
        output_module_44 = self.module_45(output_module_44)
        output_module_44 = self.module_46(output_module_44)
        output_module_36 = self.module_47(input=output_module_36, other=output_module_44, alpha=1)
        output_module_48 = self.module_48(output_module_36)
        output_module_49 = self.module_49(output_module_48)
        output_module_49 = self.module_50(output_module_49)
        output_module_51 = self.module_51(output_module_48)
        output_module_51 = self.module_52(output_module_51)
        output_module_53 = self.module_53(output_module_51)
        output_module_53 = self.module_54(output_module_53)
        output_module_55 = self.module_55(output_module_53)
        output_module_55 = self.module_56(output_module_55)
        output_module_57 = self.module_57(dim=1, tensors=[output_module_51,output_module_53,output_module_55])
        output_module_57 = self.module_58(output_module_57)
        output_module_57 = self.module_59(output_module_57)
        output_module_49 = self.module_60(input=output_module_49, other=output_module_57, alpha=1)
        output_module_61 = self.module_61(output_module_49)
        output_module_62 = self.module_62(output_module_61)
        output_module_62 = self.module_63(output_module_62)
        output_module_64 = self.module_64(output_module_61)
        output_module_64 = self.module_65(output_module_64)
        output_module_66 = self.module_66(output_module_64)
        output_module_66 = self.module_67(output_module_66)
        output_module_68 = self.module_68(output_module_66)
        output_module_68 = self.module_69(output_module_68)
        output_module_70 = self.module_70(dim=1, tensors=[output_module_64,output_module_66,output_module_68])
        output_module_70 = self.module_71(output_module_70)
        output_module_70 = self.module_72(output_module_70)
        output_module_62 = self.module_73(input=output_module_62, other=output_module_70, alpha=1)
        output_module_74 = self.module_74(output_module_62)
        output_module_75 = self.module_75(output_module_74)
        output_module_75 = self.module_76(output_module_75)
        output_module_77 = self.module_77(output_module_74)
        output_module_77 = self.module_78(output_module_77)
        output_module_79 = self.module_79(output_module_77)
        output_module_79 = self.module_80(output_module_79)
        output_module_81 = self.module_81(output_module_79)
        output_module_81 = self.module_82(output_module_81)
        output_module_83 = self.module_83(dim=1, tensors=[output_module_77,output_module_79,output_module_81])
        output_module_83 = self.module_84(output_module_83)
        output_module_83 = self.module_85(output_module_83)
        output_module_75 = self.module_86(input=output_module_75, other=output_module_83, alpha=1)
        output_module_75 = self.module_87(input=output_module_75, size=None, scale_factor=[2.0,2.0], mode='bilinear', align_corners=False)
        output_module_75 = self.module_88(output_module_75)
        output_module_75 = self.module_89(output_module_75)
        output_module_75 = self.module_90(dim=1, tensors=[output_module_75,output_module_62])
        output_module_75 = self.module_91(output_module_75)
        output_module_75 = self.module_92(output_module_75)
        output_module_93 = self.module_93(output_module_75)
        output_module_93 = self.module_94(output_module_93)
        output_module_95 = self.module_95(output_module_93)
        output_module_95 = self.module_96(output_module_95)
        output_module_97 = self.module_97(dim=1, tensors=[output_module_75,output_module_93,output_module_95])
        output_module_97 = self.module_98(output_module_97)
        output_module_97 = self.module_99(output_module_97)
        output_module_97 = self.module_100(input=output_module_97, size=None, scale_factor=[2.0,2.0], mode='bilinear', align_corners=False)
        output_module_97 = self.module_101(output_module_97)
        output_module_97 = self.module_102(output_module_97)
        output_module_97 = self.module_103(dim=1, tensors=[output_module_97,output_module_49])
        output_module_97 = self.module_104(output_module_97)
        output_module_97 = self.module_105(output_module_97)
        output_module_106 = self.module_106(output_module_97)
        output_module_106 = self.module_107(output_module_106)
        output_module_108 = self.module_108(output_module_106)
        output_module_108 = self.module_109(output_module_108)
        output_module_110 = self.module_110(dim=1, tensors=[output_module_97,output_module_106,output_module_108])
        output_module_110 = self.module_111(output_module_110)
        output_module_110 = self.module_112(output_module_110)
        output_module_110 = self.module_113(input=output_module_110, size=None, scale_factor=[2.0,2.0], mode='bilinear', align_corners=False)
        output_module_110 = self.module_114(output_module_110)
        output_module_110 = self.module_115(output_module_110)
        output_module_110 = self.module_116(dim=1, tensors=[output_module_110,output_module_36])
        output_module_110 = self.module_117(output_module_110)
        output_module_110 = self.module_118(output_module_110)
        output_module_119 = self.module_119(output_module_110)
        output_module_119 = self.module_120(output_module_119)
        output_module_121 = self.module_121(output_module_119)
        output_module_121 = self.module_122(output_module_121)
        output_module_123 = self.module_123(dim=1, tensors=[output_module_110,output_module_119,output_module_121])
        output_module_123 = self.module_124(output_module_123)
        output_module_123 = self.module_125(output_module_123)
        output_module_123 = self.module_126(input=output_module_123, size=None, scale_factor=[2.0,2.0], mode='bilinear', align_corners=False)
        output_module_123 = self.module_127(output_module_123)
        output_module_123 = self.module_128(output_module_123)
        output_module_123 = self.module_129(dim=1, tensors=[output_module_123,output_module_23])
        output_module_123 = self.module_130(output_module_123)
        output_module_123 = self.module_131(output_module_123)
        output_module_132 = self.module_132(output_module_123)
        output_module_132 = self.module_133(output_module_132)
        output_module_134 = self.module_134(output_module_132)
        output_module_134 = self.module_135(output_module_134)
        output_module_136 = self.module_136(dim=1, tensors=[output_module_123,output_module_132,output_module_134])
        output_module_136 = self.module_137(output_module_136)
        output_module_136 = self.module_138(output_module_136)
        output_module_136 = self.module_139(output_module_136)
        output_module_136 = self.module_140(input=output_module_136)
        output_module_136 = self.module_141(output_module_136)
        return output_module_136
